<?php

namespace Fytinnovations\Userconnect\Components;

use Cms\Classes\ComponentBase;
use Fytinnovations\UserConnect\Models\Subscriber;
use Lang;
use October\Rain\Database\ModelException;

class SubscriptionForm extends ComponentBase
{
    /**
     * Store whether the subscription is successful or failure
     *
     * @var innovations\UserConnect\Models\Subscriber
     */
    public Subscriber $subscriber;

    /**
     * Text to be displayed on the subscribe button
     *
     * @var string
     */
    public string $subscribeButtonText;

    /**
     * The message to be displayed when the subscription is successful
     */
    public string $successMessage;

    /**
     * The message that will be displayed when the subscription failes. This
     * will be automatically generated by the system
     * 
     * @var string
     */
    public string $failureMessage;

    public function componentDetails()
    {
        return [
            'name'        => 'fytinnovations.userconnect::lang.components.subscriptionform.name',
            'description' => 'fytinnovations.userconnect::lang.components.subscriptionform.description'
        ];
    }

    public function defineProperties()
    {
        return [
            'subscribeButtonText' => [
                'title' => 'fytinnovations.userconnect::lang.components.subscriptionform.properties.subscribeButtonText.title',
                'description' => 'fytinnovations.userconnect::lang.components.subscriptionform.properties.subscribeButtonText.description',
                'default' => Lang::get('fytinnovations.userconnect::lang.components.subscriptionform.properties.subscribeButtonText.default'),
                'type' => 'string',
            ],
            'successMessage' => [
                'title' => 'fytinnovations.userconnect::lang.components.subscriptionform.properties.successMessage.title',
                'description' => 'fytinnovations.userconnect::lang.components.subscriptionform.properties.successMessage.description',
                'default' => Lang::get('fytinnovations.userconnect::lang.components.subscriptionform.properties.successMessage.default'),
                'type' => 'string',
            ],
        ];
    }

    /**
     * {@inheritDoc}
     *
     */
    public function init(): void
    {
        $this->subscribeButtonText = $this->property('subscribeButtonText');
        $this->successMessage = $this->property('successMessage');
    }

    /**
     * Ajax handler run when the user clicks the subscribe button
     *
     * @return array
     */
    public function onSubscribe(): array
    {
        try {
            $this->subscriber = Subscriber::create(post());
        } catch (\Throwable $th) {
            if ($th instanceof ModelException) {
                $this->failureMessage = $th->getMessage();
            } else {
                $this->failureMessage = "Something went wrong.";
            }
        }

        return ['#subscription-box' => $this->renderPartial('@default')];
    }
}
